ENH: Switch to `github.com` for `flake8` pre-commit repository URL
Switch to `github.com` for the `flake8` repository URL in the pre-commit
config file.

Fixes:
```
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: could not read Username for 'https://gitlab.com': No such device or address

Check the log at /home/runner/.cache/pre-commit/pre-commit.log
Error: The process '/opt/hostedtoolcache/Python/3.8.15/x64/bin/pre-commit' failed with exit code 3
```

raised for example at:
https://github.com/jhlegarreta/tractodata/actions/runs/3669579680/jobs/6203523429#step:4:67